version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
      - postgres
    depends_on:
      - postgres
volumes:
  postgres:
networks:
  postgres:
    driver: bridge

