export enum CommonErrors {
  Unknown = 'UNKNOWN',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND_RESOURCE = 'NOT_FOUND_RESOURCE',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED'
}